In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter

from src.config import DATA
from src.utils import age_calculator, cities_comprobation

In [3]:
df=pd.read_csv(DATA)

/tmp/ipykernel_25535/2602395650.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(DATA)

In [4]:
df.head()

   Region  Country State     City  Month  Day  Year  AvgTemperature
0  Africa  Algeria   NaN  Algiers      1    1  1995            64.2
1  Africa  Algeria   NaN  Algiers      1    2  1995            49.4
2  Africa  Algeria   NaN  Algiers      1    3  1995            48.8
3  Africa  Algeria   NaN  Algiers      1    4  1995            46.4
4  Africa  Algeria   NaN  Algiers      1    5  1995            47.9

In [5]:
df.shape

(2906327, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2906327 entries, 0 to 2906326
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   Region          object
 1   Country         object
 2   State           object
 3   City            object
 4   Month           int64
 5   Day             int64
 6   Year            int64
 7   AvgTemperature  float64
dtypes: float64(1), int64(3), object(4)
memory usage: 177.4+ MB

In [7]:
df.isnull().sum()

Region                  0
Country                 0
State             1450990
City                    0
Month                   0
Day                     0
Year                    0
AvgTemperature          0
dtype: int64

In [8]:
df["Region"].nunique()

7

In [9]:
pd.DataFrame(df["Region"].value_counts())

                                     count
Region
North America                      1556681
Europe                              381990
Asia                                316663
Africa                              251118
South/Central America & Carribean   219530
Middle East                         124749
Australia/South Pacific              55596

In [10]:
df["Country"].nunique()

125

In [11]:
pd.DataFrame(df["Country"].value_counts())

                     count
Country
US                 1455337
Canada               74245
Australia            46330
China                46329
India                37063
...                    ...
Guyana                5065
Israel                4641
Burundi               4543
Georgia               4378
Serbia-Montenegro     3427

[125 rows x 1 columns]

In [12]:
df["City"].nunique()

321

In [13]:
df_city=pd.DataFrame(df["City"].value_counts())

In [14]:
df_city[df_city["count"]==18530]

               count
City
Springfield    18530
Columbus       18530
Portland       18530
Charleston     18530
Washington DC  18530
Washington     18530

In [15]:
df_country=df[df["Country"]=="US"]

In [16]:
df_country.head()

,Region,Country,State,City,Month,Day,Year,AvgTemperature
1450990,North America,US,Alabama,Birmingham,1,1,1995,50.7
1450991,North America,US,Alabama,Birmingham,1,2,1995,37.2
1450992,North America,US,Alabama,Birmingham,1,3,1995,33.2
1450993,North America,US,Alabama,Birmingham,1,4,1995,33.3
1450994,North America,US,Alabama,Birmingham,1,5,1995,26.4

In [17]:
df_country.isnull().sum()

Region            0
Country           0
State             0
City              0
Month             0
Day               0
Year              0
AvgTemperature    0
dtype: int64

In [18]:
df_election=df[df["City"].isin(["Springfield","Columbus","Portland","Charleston","Washington DC","Washington"])]

In [19]:
df_election["Year"].value_counts()

Year
1996    4392
2000    4392
2004    4392
2016    4392
2012    4392
2008    4392
1999    4380
1995    4380
1998    4380
1997    4380
2003    4380
2002    4380
2001    4380
2006    4380
2007    4380
2009    4380
2010    4380
2005    4380
2011    4380
2013    4380
2014    4380
2015    4380
2017    4380
2018    4380
2019    4380
2020    1608
Name: count, dtype: int64

In [20]:
df_election["City"].value_counts()

City
Washington       18530
Washington DC    18530
Columbus         18530
Springfield      18530
Portland         18530
Charleston       18530
Name: count, dtype: int64

In [21]:
years=df_election["Year"].unique()

In [22]:
age_calculator(years,df_election)

Year  City
1995  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
1996  Charleston       732
      Columbus         732
      Portland         732
      Springfield      732
      Washington       732
      Washington DC    732
Name: count, dtype: int64
Year  City
1997  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
1998  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
1999  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2000  Charleston       732
      Columbus         732
      Portland         732
      Springfield      732
      Washington       732
      Washington DC    732
Name: count, dtype: int64
Year  City
2001  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2002  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2003  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2004  Charleston       732
      Columbus         732
      Portland         732
      Springfield      732
      Washington       732
      Washington DC    732
Name: count, dtype: int64
Year  City
2005  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2006  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2007  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2008  Charleston       732
      Columbus         732
      Portland         732
      Springfield      732
      Washington       732
      Washington DC    732
Name: count, dtype: int64
Year  City
2009  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2010  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2011  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2012  Charleston       732
      Columbus         732
      Portland         732
      Springfield      732
      Washington       732
      Washington DC    732
Name: count, dtype: int64
Year  City
2013  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2014  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2015  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2016  Charleston       732
      Columbus         732
      Portland         732
      Springfield      732
      Washington       732
      Washington DC    732
Name: count, dtype: int64
Year  City
2017  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2018  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2019  Charleston       730
      Columbus         730
      Portland         730
      Springfield      730
      Washington       730
      Washington DC    730
Name: count, dtype: int64
Year  City
2020  Charleston       268
      Columbus         268
      Portland         268
      Springfield      268
      Washington       268
      Washington DC    268
Name: count, dtype: int64

In [23]:
df_copy= df_election[df_election["City"]=="Columbus"]

df_copy["State"].value_counts()

State
Georgia    9265
Ohio       9265
Name: count, dtype: int64

In [24]:
cities= ["Springfield","Columbus","Portland","Charleston","Washington DC","Washington"]

In [26]:
cities_comprobation(cities,df_election)

NAME : Springfield
State
Illinois    9265
Missouri    9265
Name: count, dtype: int64
----------------------------------------
NAME : Columbus
State
Georgia    9265
Ohio       9265
Name: count, dtype: int64
----------------------------------------
NAME : Portland
State
Maine     9265
Oregon    9265
Name: count, dtype: int64
----------------------------------------
NAME : Charleston
State
South Carolina    9265
West Virginia     9265
Name: count, dtype: int64
----------------------------------------
NAME : Washington DC
State
Maryland    18530
Name: count, dtype: int64
----------------------------------------
NAME : Washington
State
District of Columbia    18530
Name: count, dtype: int64
----------------------------------------

In [29]:
df_washington=df_election[df_election["City"]=="Washington DC"]

In [35]:
df_washington[df_washington.duplicated()]

,Region,Country,State,City,Month,Day,Year,AvgTemperature
1696320,North America,US,Maryland,Washington DC,1,1,1995,40.6
1696321,North America,US,Maryland,Washington DC,1,2,1995,39.8
1696322,North America,US,Maryland,Washington DC,1,3,1995,29.3
1696323,North America,US,Maryland,Washington DC,1,4,1995,33.0
1696324,North America,US,Maryland,Washington DC,1,5,1995,20.9
...,...,...,...,...,...,...,...,...
1705580,North America,US,Maryland,Washington DC,5,9,2020,45.2
1705581,North America,US,Maryland,Washington DC,5,10,2020,50.2
1705582,North America,US,Maryland,Washington DC,5,11,2020,56.1
1705583,North America,US,Maryland,Washington DC,5,12,2020,52.5
1705584,North America,US,Maryland,Washington DC,5,13,2020,53.4

In [38]:
df=df_election[(df_election["City"] == "Columbus") & (df_election["State"] == "Ohio")]