In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter

from src.config import DATA

In [2]:
df=pd.read_csv(DATA)

/tmp/ipykernel_104231/2602395650.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(DATA)

In [3]:
df.head()

   Region  Country State     City  Month  Day  Year  AvgTemperature
0  Africa  Algeria   NaN  Algiers      1    1  1995            64.2
1  Africa  Algeria   NaN  Algiers      1    2  1995            49.4
2  Africa  Algeria   NaN  Algiers      1    3  1995            48.8
3  Africa  Algeria   NaN  Algiers      1    4  1995            46.4
4  Africa  Algeria   NaN  Algiers      1    5  1995            47.9

In [5]:
df.shape

(2906327, 8)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2906327 entries, 0 to 2906326
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   Region          object
 1   Country         object
 2   State           object
 3   City            object
 4   Month           int64
 5   Day             int64
 6   Year            int64
 7   AvgTemperature  float64
dtypes: float64(1), int64(3), object(4)
memory usage: 177.4+ MB

In [10]:
df.isnull().sum()

Region                  0
Country                 0
State             1450990
City                    0
Month                   0
Day                     0
Year                    0
AvgTemperature          0
dtype: int64

In [11]:
df["Region"].nunique()

7

In [14]:
pd.DataFrame(df["Region"].value_counts())

                                     count
Region
North America                      1556681
Europe                              381990
Asia                                316663
Africa                              251118
South/Central America & Carribean   219530
Middle East                         124749
Australia/South Pacific              55596

In [15]:
df["Country"].nunique()

125

In [16]:
pd.DataFrame(df["Country"].value_counts())

                     count
Country
US                 1455337
Canada               74245
Australia            46330
China                46329
India                37063
...                    ...
Guyana                5065
Israel                4641
Burundi               4543
Georgia               4378
Serbia-Montenegro     3427

[125 rows x 1 columns]

In [17]:
df["City"].nunique()

321

In [18]:
pd.DataFrame(df["City"].value_counts())

               count
City
Springfield    18530
Columbus       18530
Portland       18530
Charleston     18530
Washington DC  18530
...              ...
Frankfurt       4136
Flagstaff       3574
Pristina        3427
Yerevan         3226
Bonn            3133

[321 rows x 1 columns]